POST https://socially-5u3q.onrender.com/signup/
Content-Type: application/json

{
  "firstName":"ali",
  "lastName":"b",
    "email":"alib@email.com",
    "password":"1234",
       "birthDate":"2015-5-7",
        "gender":"male"
}

###
POST https://socially-uemy.onrender.com/login/
Content-Type: application/json

{
  "email":"alib@email.com",
  "password":"1234"
}
###
POST https://socially-uemy.onrender.com/verify_account/
Content-Type: application/json

{
  "email":"alib@email.com",
  "code":"533157"
}
###
###ddd
GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
###
GET http://localhost:3001/posts/6558e148af2cfd924d1a6290
###
POST http://localhost:3001/posts/create_post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDAzMDQ0ZDE4YzYxNmQ4MjdjNWZlNCIsImlhdCI6MTY5ODc1NzUwOCwiZXhwIjoxNjk5OTY3MTA4fQ.qxgSmwYh-D24_dDcW93OXktkcj-Zbvrb3zlcNp18iz0


{ "text":"random description", "picturePath":"gsders","location":"benghazi" }
###
PATCH  http://localhost:3001/posts/edit_post/651893253a3d401d8d97a459
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

{ "description":"hi", "picturePath":"gsders","location":"benghazi" }
###
PATCH  http://localhost:3001/posts/delete_comment/655b952cb6ccf1900f3478f0/655de37da20933679d2a5300/65653a360e125ac80ea0b5d7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWI5NTJjYjZjY2YxOTAwZjM0NzhmMCIsImlhdCI6MTcwMDUwMDgxMCwiZXhwIjoxNzAxMzY0ODEwfQ.EUNa05M03ol-sCYmmu69raHJ62fmpEU5Yr8TvYTKlgk

{ "comment":"hello"}
###
PATCH  http://localhost:3001/posts/edit_post/655c9f82e85104860f0a3491/655e69e002c6903b7fd5727c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWM5ZjgyZTg1MTA0ODYwZjBhMzQ5MSIsImlhdCI6MTcwMDY3MTMzNCwiZXhwIjoxNzAxNTM1MzM0fQ.bGM13SeNIDwNJxesGwY3xNnwgwE7vj0oAW_REkZsEqE

{ "text":"مرحبًا"}
###
PATCH  http://localhost:3001/posts/delete_reply/651893253a3d401d8d97a459/651890ca23160911617b981a/651890f023160911617b981e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

###
PATCH  http://localhost:3001/posts/edit_reply/651893253a3d401d8d97a459/651890ca23160911617b981a/651890f023160911617b981e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

{ "reply":"shello"}
###
PATCH  http://localhost:3001/posts/like_reply/651893253a3d401d8d97a459/651890ca23160911617b981a/6518915123160911617b9828
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
###
PATCH  http://localhost:3001/posts/like_comment/651893253a3d401d8d97a459/651890ca23160911617b981a/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw


###
###
POST http://localhost:3001/posts/add_comment/65676fc87142433e54f9ac76/65701f0b82d35ba3e7de5457
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Njc2ZmM4NzE0MjQzM2U1NGY5YWM3NiIsImlhdCI6MTcwMTI3NzY2MiwiZXhwIjoxNzAyMTQxNjYyfQ.sAss3y9rfLkxqIzhmC31B2peBkr0UdHes7hW9qKK0KE
Content-Type: application/json

{"text":"hi"}
###
GET http://localhost:3001/saved_posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Njc2ZmM4NzE0MjQzM2U1NGY5YWM3NiIsImlhdCI6MTcwMTI3NzY2MiwiZXhwIjoxNzAyMTQxNjYyfQ.sAss3y9rfLkxqIzhmC31B2peBkr0UdHes7hW9qKK0KE

###
PATCH  http://localhost:3001/user/follow/64fde60ff9697bdc0c4bfcbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

###eyad
Patch  http://localhost:3001/user/unfollow/64fde60ff9697bdc0c4bfcbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

###
PATCH http://localhost:3001/user/remove_follower/64fde60ff9697bdc0c4bfcbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
###eyad

GET  http://localhost:3001/user/following/64fde60ff9697bdc0c4bfcbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw

###
GET http://localhost:3001/posts/64eab67712acb3c6c23cb870/64eb4197184b8eac3e15fbe6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
###
GET http://localhost:3001/posts/reaction_details/651893253a3d401d8d97a459

###
PATCH http://localhost:3001/posts/post_like_toggle/655904d6d1b73895c8fa9b8f/655b42cb7ec4a7c8dc1e7423
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTkwNGQ2ZDFiNzM4OTVjOGZhOWI4ZiIsImlhdCI6MTcwMDMzMjc4MSwiZXhwIjoxNzAxMTk2NzgxfQ.DuumX5E2g8KniLLL0jz0KaHX6eCmxsNqsdlPKZnJFcg

###
DELETE  http://localhost:3001/posts/delete_post/655904d6d1b73895c8fa9b8f/65590514d1b73895c8fa9b9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTkwNGQ2ZDFiNzM4OTVjOGZhOWI4ZiIsImlhdCI6MTcwMDMzMjc4MSwiZXhwIjoxNzAxMTk2NzgxfQ.DuumX5E2g8KniLLL0jz0KaHX6eCmxsNqsdlPKZnJFcg

###
PATCH http://localhost:3001/posts/delete_comment/651893253a3d401d8d97a459/651893d03a3d401d8d97a45d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
###
PATCH http://localhost:3001/posts/delete_comment/651b3441285615be7527723d/651b3c969a892aa2762c4b93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MTg4ZDNhOTIwNGY4ZjJiMzlkYTdmZCIsImlhdCI6MTY5NjEwNzg0MywiZXhwIjoxNjk3MzE3NDQzfQ.vT7P3otks2zGnVxdw1lgS580a0m8wzWH_vzJovadwaw
Content-Type: application/json

{"comment":true}